apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:AJo8+lsArDvclTYqn+Q1QRFMXJTEE+EzfHY+RQlhEmBgIhRGkyu4rNqZNX7URmcTxiafwrmX7g5gmcRG/t+lCaUjHtBFTaIJXN6K2A9/dfGgbDoQa5LsCmCxMXrwXg==,iv:kFw8L2bwEwWNfsf9/6y8LqxtzeNjPb4p4dxnnpzL6a4=,tag:Z/JZ6fZp0BZalALLQb46sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2xjundtade098xkcrfpkssv2daykl74tlmuypajrap0l4meh4xqp29xfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQk9CUWo4TEdnMUNUazA0
            T3JOeVlmaVNYaEZLeHRZUjVCaTZTZEVFMmpJCjNkbHJtLy9wVnJGM2FHR0JUVlJt
            L2dTT1h5UGhNRzJPbElLM1dUQlEzMFEKLS0tIERJUkx2OHBpSWZucWwxdjFnYnpz
            QW9pbnZsSS9uMjA2RStiZ2lyZG05d00KK1EBk7OVJ8JZj0Rf1OZk0Fs4iKashcF1
            NRBZRHy9c3YyEFr55TRgYO2XcAk0v9zIwI9he3MKQ4NxTsnPeoZlqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-11T01:57:02Z"
    mac: ENC[AES256_GCM,data:p/myVlgfHJzB1qqtuL14JlV6ouhC9KMr0heP97ClMJzMHIZ0p5yEOQnVJpnxtgZsHU271HJK00trlLLpPaHDLvv2uLDc9G7VkQHuOMaJ3J0Mb18t4mYFcfXHWOSHxieckxxAr2qOb33PTzDqSywQwm+oO26KIHbKlOJVkE29Sg4=,iv:4gxtegBtJSVadeWW3xG8S+RNMgK9DxmVit6kQMq6M04=,tag:x+Oh78jKJuBOx+A4u7fOzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
